apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: monitoring
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      app: grafana
  endpoints:
    - port: service
