apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
    - port: metrics
