apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: grafana
data:
  grafana.ini: |-
    [analytics]
    reporting_enabled = false
    check_for_updates = true

    [log]
    mode = console

    [auth.basic]
    enabled = false

    [auth.anonymous]
    enabled = true
    org_role = Viewer

    [auth]
    disable_login_form = true

    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    http_port = 3000

    [security]
    disable_gravatar = true

    [metrics]
    enabled = true
    disable_total_stats = false
